workspace:
  base: /go
  path: src/github.com/Rukenshia/soccerstreams

pipeline:
  dependencies:
    image: golang
    commands:
    - make deps

  test:
    group: qa
    image: golang
    commands:
    - make test

  lint:
    group: qa
    image: golang
    commands:
    - make lint || exit 0

  build-agent-bin:
    group: build
    image: ruken/docker-go-gcr:latest
    pull: true
    environment:
      GOPATH: /go
      DOCKER_HOST: tcp://docker:2375
    secrets:
    - source: gcr
      target: gcr_service_account
    - source: ca_certificates
    commands:
    - echo "$CA_CERTIFICATES" > cmd/agent/ca-certificates.pem
    - make agent
  build-sweeper:
    group: build
    image: ruken/docker-go-gcr:latest
    pull: true
    environment:
      GOPATH: /go
      DOCKER_HOST: tcp://docker:2375
    secrets:
    - source: gcr
      target: gcr_service_account
    - source: ca_certificates
    commands:
    - echo "$CA_CERTIFICATES" > cmd/sweeper/ca-certificates.pem
    - make sweeper
  build-web:
    group: build
    image: ruken/docker-go-gcr:latest
    pull: true
    environment:
      GOPATH: /go
      DOCKER_HOST: tcp://docker:2375
    secrets:
    - source: gcr
      target: gcr_service_account
    commands:
    - make deps web
  
  notify:
    branch: master
    image: appleboy/drone-telegram
    format: html
    secrets:
    - source: telegram_user
      target: telegram_to
    - source: telegram_token
      target: telegram_token
    when:
      status: [ success, failure ]
    message: |
      {{#success build.status}}
        &#x1F680 build {{repo.name}}#{{build.number}} succeeded.
      {{else}}
        &#x1F534 build {{repo.name}}#{{build.number}} failed.
      {{/success}}

services:
  docker:
    image: docker:dind
    command: [ "--tls=false" ]
    privileged: true