apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: soccerstreams-sweeper-deployment
  labels:
    app: soccerstreams-sweeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccerstreams-sweeper
  template:
    metadata:
      labels:
        app: soccerstreams-sweeper
    spec:
      containers:
      - name: soccerstreams-sweeper
        image: gcr.io/soccerstreams-web/sweeper:1.0.4
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0.05"
        volumeMounts:
        - name: gcloud
          mountPath: "/opt/soccerstreams/gcloud"
        env:
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: sentry-sweeper
                key: sentry
      volumes:
      - name: gcloud
        secret:
          secretName: gcloud-service-account