apiVersion: v1
kind: Service
metadata:
  name: soccerstreams-web-service
  labels:
    run: soccerstreams-web-service
spec:
  type: LoadBalancer
  ports:
  - name: metrics
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: soccerstreams-web
