workspace:
  base: /go
  path: src/github.com/Rukenshia/soc-web

pipeline:
  dependencies:
    image: golang
    commands:
    - go get -v ./...

  test:
    group: qa
    image: golang
    commands:
    - go test ./...

  lint:
    group: qa
    image: golang
    commands:
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install
    - gometalinter --fast ./... || exit 0

  build:
    image: golang
    commands:
    - go get github.com/revel/cmd/revel
    - GOOS=linux revel package github.com/Rukenshia/soc-web prod

  upload:
    branch: master
    image: appleboy/drone-scp
    source: soc-web.tar.gz
    target: "/root/soc-web/drone_ci_${DRONE_COMMIT_SHA}"
    host: server.in.fkn.space
    secrets:
    - ssh_username
    - ssh_key

  run:
    branch: master
    image: appleboy/drone-ssh
    host: server.in.fkn.space
    secrets:
    - ssh_username
    - ssh_key
    script:
    - cd soc-web
    - killall soc-web
    - "mv drone_ci_${DRONE_COMMIT_SHA}/soc-web.tar.gz soc-web.tar.gz"
    - "rm -r drone_ci_${DRONE_COMMIT_SHA}"
    - tar -xzf soc-web.tar.gz
    - ./run.sh > /dev/null 2>&1 &

  notify:
    branch: master
    image: appleboy/drone-telegram
    format: html
    secrets:
    - source: telegram_user
      target: telegram_to
    - source: telegram_token
      target: telegram_token
    when:
      status: [ success, failure ]
    message: |
      {{#success build.status}}
        &#x1F680 build {{repo.name}}#{{build.number}} succeeded.
      {{else}}
        &#x1F534 build {{repo.name}}#{{build.number}} failed.
      {{/success}}
